"""initial migration

Revision ID: 4eb8b05bf8e0
Revises: None
Create Date: 2016-05-16 17:52:49.802772

"""

# revision identifiers, used by Alembic.
revision = '4eb8b05bf8e0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
